use_frameworks!

platform :ios, '10.0'

target 'GPagerKit_Example' do
  pod 'GPagerKit', :path => '../'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'FDFullscreenPopGesture'
  target 'GPagerKit_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
